version: 2

sources:
  - name: brooklyndata
    database: bd_raw 
    schema: brooklyndata
    tables:
      - name: olist_geolocation
      - name: olist_orders
      - name: olist_order_customer
      - name: olist_order_items
      - name: olist_order_payments
      - name: olist_order_reviews
      - name: olist_products
      - name: olist_sellers
